import { test, expect } from '@playwright/test'

test('Czech default, complete language switch, stored preference', async ({ page }) => {
  const errors:string[]=[]
  page.on('pageerror', error=>errors.push(error.message))
  await page.goto('./')
  await expect(page.locator('html')).toHaveAttribute('lang','cs')
  await expect(page.getByRole('heading',{level:1})).toContainText('kondenzátor')
  await page.getByRole('button',{name:'Switch to English'}).click()
  await expect(page.getByRole('heading',{name:'Hear what a capacitor changes'})).toBeVisible()
  await expect(page.getByRole('slider',{name:'Resistance R',exact:true})).toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang','en')
  await expect(page.getByTestId('cutoff')).toHaveText('72.3 Hz')
  expect(errors).toEqual([])
})

test('cutoff identity, presets, and knob share one circuit state', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button',{name:'Switch to English'}).click()
  await page.getByRole('button',{name:'Set f to cutoff frequency'}).click()
  await expect(page.getByTestId('gain')).toHaveText('-3.01 dB')
  await page.getByRole('combobox',{name:'Educational preset'}).selectOption('0')
  await expect(page.getByTestId('cutoff')).toHaveText('15.9 Hz')
  await expect(page.getByRole('button',{name:'Set f to cutoff frequency'})).toBeDisabled()
  const knob=page.getByRole('slider',{name:'Rotary resistance control'})
  await knob.focus();await knob.press('End')
  await expect(knob).toHaveAttribute('aria-valuenow','1000000')
  await expect(page.getByTestId('cutoff')).toHaveText('1.59 Hz')
  await knob.press('Home')
  await expect(page.getByTestId('cutoff')).toHaveText('159 Hz')
  const box=await knob.boundingBox()
  expect(box).not.toBeNull()
  await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2)
  await page.mouse.down();await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2-30,{steps:5});await page.mouse.up()
  expect(Number(await knob.getAttribute('aria-valuenow'))).toBeGreaterThan(10000)
})

test('charging checkpoint, pause, discharge, zero voltage', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button',{name:'Switch to English'}).click()
  await page.getByRole('button',{name:'Charging & energy'}).click()
  await page.getByRole('button',{name:'Jump to τ'}).click()
  await expect(page.getByTestId('uc')).toHaveText('3.16 V')
  await expect(page.getByTestId('heat')).toHaveText('238 nJ')
  await page.getByRole('button',{name:'Reset',exact:true}).click()
  await expect(page.getByTestId('uc')).toHaveText('0 V')
  await page.getByRole('button',{name:'Play transition'}).click()
  await expect.poll(async()=>Number(await page.getByRole('slider',{name:'Time in time constants'}).inputValue())).toBeGreaterThan(0.05)
  await page.getByRole('button',{name:'Pause',exact:true}).click()
  const paused=await page.getByRole('slider',{name:'Time in time constants'}).inputValue()
  await page.waitForTimeout(120)
  expect(await page.getByRole('slider',{name:'Time in time constants'}).inputValue()).toBe(paused)
  await page.getByRole('combobox',{name:'Process'}).selectOption('discharging')
  await page.getByRole('button',{name:'Jump to τ'}).click()
  await expect(page.getByTestId('uc')).toHaveText('1.84 V')
  await page.getByRole('slider',{name:'Source voltage U',exact:true}).fill('0')
  await page.getByRole('button',{name:'Jump to τ'}).click()
  await expect(page.getByTestId('uc')).toHaveText('0 V')
  await expect(page.getByTestId('heat')).toHaveText('0 J')
  await expect(page.locator('body')).not.toContainText('NaN')
})

test('audio starts by gesture, switches A/B, retunes and stops', async ({ page }) => {
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('./')
  await page.getByRole('button',{name:'Switch to English'}).click()
  await page.getByRole('button',{name:'▶ Start audio'}).click()
  await expect(page.getByRole('button',{name:'Stop audio'})).toBeVisible()
  await page.getByRole('button',{name:'Bypass',exact:true}).click()
  await expect(page.getByRole('button',{name:'Bypass',exact:true})).toHaveAttribute('aria-pressed','true')
  for (const value of ['3','0','2','1']) await page.getByRole('combobox',{name:'Educational preset'}).selectOption(value)
  await page.getByRole('button',{name:'Filtered',exact:true}).click()
  await page.getByRole('combobox',{name:'Sound',exact:true}).selectOption('bass')
  await page.getByRole('button',{name:'Stop audio'}).click()
  await expect(page.getByRole('button',{name:'▶ Start audio'})).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('mobile, reduced motion, real photographs and no horizontal overflow', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('./')
  await expect(page.getByRole('button',{name:'Switch to English'})).toBeVisible()
  await page.getByRole('button',{name:'Nabíjení a energie',exact:true}).click()
  await expect(page.getByRole('button',{name:'Spustit děj',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  for(const img of await page.locator('.component-photos img').all()) {
    await img.scrollIntoViewIfNeeded()
    await expect.poll(()=>img.evaluate((node:HTMLImageElement)=>node.naturalWidth)).toBeGreaterThan(100)
  }
})
